---
# tasks file for docker
- name: Install packages for docker to use
  package:
    name={{ item }}
    state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
  when: ansible_os_family == 'Debian'

- name: Adding docker apt-key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D
  when: ansible_os_family == 'Debian'

- name: Adding docker repo
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo debian-jessie main'
  when: ansible_os_family == 'Debian'

- name: apt-get update
  apt:
    update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install docker (DEB)
  package:
    name=docker-engine
    state=latest
  when: ansible_os_family == 'Debian'

- name: Install docker (RHEL)
  package:
    name=docker
    state=latest
  when: ansible_os_family == "RedHat"
